# Generated by Django 5.1.1 on 2024-10-15 16:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_like'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='denied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='video',
            name='link',
            field=models.URLField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'video')},
        ),
    ]
